### PR TITLE
MVC6 updated to RC1

### PR DESCRIPTION
**Pull request by mcliment**
Updated MVC6 references to rc1-final and changed code accordingly.

WebAPI sample is not touched, still in beta7, waiting for Swashbuckle to update to rc1.

### CODE REVIEW

**Comment by RehanSaeed** [comment]
I've found a bug in VS I think. See the link for more info. @mcliment Did you get around this issue?

**Comment by mcliment** [comment]
Sorry for the delay, I tested today with latest BP from upstream and worked without much trouble. ;-)

**Comment by RehanSaeed** [comment]
Hmmmm, must be my installation that has gotten messed up somehow.

**Comment by RehanSaeed** [comment]
@mcliment I've now tried one two machines. [This](https://github.com/aspnet/Tooling/issues/300) bug definitely exists in RC1 as a show stopper. Did you do anything special to get around it?

**Pull request merged**
